export { default as Homepage } from "./Homepage";
export { default as Header } from "./Header";
export { default as HeroSection } from "./HeroSection";
export { default as FeaturesSection } from "./FeaturesSection";
export { default as FreeForeverSection } from "./FreeForeverSection";
export { default as DonationSection } from "./DonationSection";
export { default as CTASection } from "./CTASection";
export { default as Footer } from "./Footer";
export { default as PrivacySection } from "./PrivacySection";
